    - name: Установка MariaDB Server
      yum:
        name: mariadb105-server
        state: present

    - name: Ensure MySQL is running and enabled
      service:
        name: mariadb
        state: started
        enabled: yes

    
    - name: Create MySQL user and grant privileges on the database
      mysql_user:
        name: "{{ MYSQL_USER }}"
        password: "{{ MYSQL_PASSWORD }}"
        priv: "{{ MYSQL_DB }}.*:ALL"
        host: all
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
        login_user: root



    - name: Create MySQL database
      mysql_db:
        name: flask_db     
        login_user: root
        login_unix_socket: /var/lib/mysql/mysql.sock 
        state: present
      register: mysql_db_result


    - name: Show available databases
      command: mysql -e "SHOW DATABASES;"
      register: mysql_show_databases

    - debug:
        var: mysql_show_databases.stdout_lines

    - name: Update packages using dnf
      dnf:
        name: "*"
        state: latest

    - name: Install additional packages
      yum:
        name: python3-pip
        state: present
   

    - name: set mysql to listen on external ip
      replace:
        path: /etc/my.cnf
        regexp: 127.0.0.1
        replace: 0.0.0.0


